runtime: nodejs8
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  SERVICE_ACCOUNT: ""
handlers:
- url: /(.*\.svg)
  static_files: static/\1
  upload: static/(.*\.svg)
- url: /(.*\.js)
  static_files: dist/\1
  upload: dist/(.*\.js)
- url: /(.*\.map)
  mime_type: application/octet-stream
  static_files: dist/\1
  upload: dist/(.*\.map)
- url: (.*)/(login|register|dashboard)?
  static_files: dist/index.html
  upload: dist
- url: (.*)
  static_files: dist/index.html
  upload: dist
